---Generated by profile builder---
---Avoidance thread Setup---
AddNameToObjectAvoidWhiteList("Earthroot")
AddNameToObjectAvoidWhiteList("Silverleaf")
AddNameToObjectAvoidWhiteList("Peacebloom")
AddNameToObjectAvoidWhiteList("Mageroyal")
AddNameToObjectAvoidWhiteList("Briarthorn")

StartMobAvoidance()
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 1619
IDs[2] = 1617
IDs[3] = 1618
IDs[4] = 1620
IDs[5] = 1621

--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10456.08
StartingPoint[2] = 962.3741
StartingPoint[3] = 35.10577
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat)