---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Venom Web Spider")
AddNameToAvoidWhiteList("Dire Wolf")
AddNameToAvoidWhiteList("Rabid Dire Wolf")

StartMobAvoidance()

UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(30)
SetQuestSellAt(2)

BlackListRepairVendorByName("Antonio Perelli");
BlackListSellVendorByName("Antonio Perelli");
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 217
IDs[2] = 43704
IDs[3] = 565

--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10069.11
StartingPoint[2] = -1142.305
StartingPoint[3] = 29.77963
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),500,StartingFloat,true)