---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Mesa Buzzard")
AddNameToAvoidWhiteList("Giant Plains Creeper")
AddNameToAvoidWhiteList("Highland Fleshstalker")
AddNameToAvoidWhiteList("Highland Trasher")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2579
IDs[2] = 2565
IDs[3] = 2561
IDs[4] = 2560
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1261.255
StartingPoint[2] = -2513.765
StartingPoint[3] = 20.73603
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),500,StartingFloat)