---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Boulderfist Ogre")
AddNameToAvoidWhiteList("Witherbark Shadowcaster")
AddNameToAvoidWhiteList("Boulderfist Enforcer")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2562
IDs[2] = 2553
IDs[3] = 2564
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1248.843
StartingPoint[2] = -2129.871
StartingPoint[3] = 80.29011
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat)