---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Boulderfist Brute")
AddNameToAvoidWhiteList("Boulderfist Magus")
AddNameToAvoidWhiteList("Young Mesa Buzzard")
AddNameToAvoidWhiteList("Elder Mesa Buzzard")
AddNameToAvoidWhiteList("Highland Fleshstalker")
StartMobAvoidance()

UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(30)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2566
IDs[2] = 2567
IDs[3] = 2578
IDs[4] = 2580
IDs[5] = 2561
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1921.267
StartingPoint[2] = -2646.581
StartingPoint[3] = 70.8086
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat,true)