---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highland Strider")
StartMobAvoidance()

UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2559
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1242.586
StartingPoint[2] = -2201.518
StartingPoint[3] = 57.10775
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat)