---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highland Fleshstalker")
AddNameToAvoidWhiteList("Giant Plains Creeper")
AddNameToAvoidWhiteList("Elder Mesa Buzzard")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2561
IDs[2] = 2565
IDs[3] = 2580
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1715.112
StartingPoint[2] = -2646.707
StartingPoint[3] = 44.18851
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),400,StartingFloat,true)