---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Burning Exile")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2760
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -903.0722
StartingPoint[2] = -1749.605
StartingPoint[3] = 46.18821
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),150,StartingFloat)