---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Greater Rock Elemental")
StartMobAvoidance()
BlackListSellVendorByName("Yuka Screwspigot");
 BlackListRepairVendorByName("Yuka Screwspigot");
BlackListSellVendorByName("Gruna");
 BlackListRepairVendorByName("Gruna");
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2736
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -7240.709
StartingPoint[2] = -2184.809
StartingPoint[3] = 294.4308
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),160,StartingFloat)