---Generated by profile builder---
---Avoidance thread Setup---
AddNameToObjectAvoidWhiteList("Battered Footlocker")

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 179490
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -3174.65
StartingPoint[2] = -1165.777
StartingPoint[3] = 7.929537
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat)