---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Splinter Fist Ogre")
AddNameToAvoidWhiteList("Splinter Fist Fire Weaver")
AddNameToAvoidWhiteList("Splinter Fist Taskmaster")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)

    BlackListSellVendorByName("Jaquilina Dramet");
    BlackListRepairVendorByName("Jaquilina Dramet");

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 889
IDs[2] = 891
IDs[3] = 892
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10975.27
StartingPoint[2] = -261.989
StartingPoint[3] = 20.75447
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat)