---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Young Black Ravager")
AddNameToAvoidWhiteList("Splinter Fist Ogre")
AddNameToAvoidWhiteList("Splinter Fist Fire Weaver")
AddNameToAvoidWhiteList("Splinter Taskmaaster")
StartMobAvoidance()

UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(30)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 923
IDs[2] = 889
IDs[3] = 891
IDs[4] = 892
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10976.74
StartingPoint[2] = -261.9306
StartingPoint[3] = 20.8188
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat,true)