---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Rumbling Exile")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2592
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -1505.709
StartingPoint[2] = -2282.157
StartingPoint[3] = 47.24806
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat)