---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Enraged Rock Elemental")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2791
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -7228.508
StartingPoint[2] = -3418.468
StartingPoint[3] = 290.6251
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),150,StartingFloat)