---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Longtooth Runner")
AddNameToAvoidWhiteList("Hatecrest Screamer")
AddNameToAvoidWhiteList("Hatecrest Warrior")
AddNameToAvoidWhiteList("Hatecrest Wave Rider")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 5286
IDs[2] = 5335
IDs[3] = 5331
IDs[4] = 5332
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -4696.656
StartingPoint[2] = 3450.872
StartingPoint[3] = 22.08435
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat,true)