
---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Fetid Corpse")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 1270
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10280.11
StartingPoint[2] = -1307.977
StartingPoint[3] = 47.27188
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),200,StartingFloat)