---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Vicious Owlbeast")
AddNameToAvoidWhiteList("Silvermane Wolf")
AddNameToAvoidWhiteList("Witherbark Zealot")
AddNameToAvoidWhiteList("Witherbark Scalper")
AddNameToAvoidWhiteList("Witherbark Venomblood")
AddNameToAvoidWhiteList("Witherbark Hideskinner")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2927
IDs[2] = 2924
IDs[3] = 2650
IDs[4] = 2649
IDs[5] = 2652
IDs[6] = 2651
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 78.35502
StartingPoint[2] = -2690.44
StartingPoint[3] = 110.5448
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),500,StartingFloat,true)