---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Mangy Silvermane")
AddNameToAvoidWhiteList("Witherbark Zealot")
AddNameToAvoidWhiteList("Witherbark Scalper")
StartMobAvoidance()
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2923
IDs[2] = 2650
IDs[3] = 2649
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 38.75607
StartingPoint[2] = -2420.243
StartingPoint[3] = 125.2265
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat,true)