---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Mottled Raptor")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(40)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 1020
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -3286.06
StartingPoint[2] = -1732.588
StartingPoint[3] = 11.01359
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),500,StartingFloat)