---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Scalding Whelp")
BlackListSellVendorByName("Prospector Ryedol");
 BlackListRepairVendorByName("Prospector Ryedol");
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2725
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -6870.047
StartingPoint[2] = -3891.372
StartingPoint[3] = 264.8893
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),150,StartingFloat,true)