---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Blazing Elemental")
AddNameToAvoidWhiteList("Tempered War Golem")
AddNameToAvoidWhiteList("Magma Elemental")
AddNameToAvoidWhiteList("Inferno Elemental")
AddNameToAvoidWhiteList("Heavy War Golem")
StartMobAvoidance()

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 11703

SetQuestRepairVendors(TableToList(VendorIDs))

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 5850
IDs[2] = 5853
IDs[3] = 5855
IDs[4] = 5852
IDs[5] = 5854
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -7078.477
StartingPoint[2] = -1331.546
StartingPoint[3] = 262.7708
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),500,StartingFloat,false,"",false)