---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Scorpid Tail Lasher")
AddNameToAvoidWhiteList("Blisterpaw Hyena")
AddNameToAvoidWhiteList("Glaasshide Basilisk")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(50)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 5423
IDs[2] = 5426
IDs[3] = 5419
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -7235.459
StartingPoint[2] = -3829.197
StartingPoint[3] = 11.08044
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),1000,StartingFloat,true)