---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Glasshide Petrifier")
AddNameToAvoidWhiteList("Rabid Blisterpaw")
AddNameToAvoidWhiteList("Scorpid Dunestalker")
StartMobAvoidance()

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 5411

SetQuestRepairVendors(TableToList(VendorIDs))

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 5421
IDs[2] = 5427
IDs[3] = 5424
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -8859.65
StartingPoint[2] = -2863.329
StartingPoint[3] = 34.95265
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),800,StartingFloat,true,"",false)