---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Red Whelp")
AddNameToAvoidWhiteList("Lost Whelp")
AddNameToAvoidWhiteList("Crimson Whelp")
AddNameToAvoidWhiteList("Flamesnorting Whelp")
StartMobAvoidance()
UseDBToRepair(true)
UseDBToSell(true)
SetQuestRepairAt(30)
SetQuestSellAt(2)
local InRangeSpawns = {}
local IDs = {}
IDs[1] = 1042
IDs[2] = 1043
IDs[3] = 1069
IDs[4] = 1044
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -3283.938
StartingPoint[2] = -3063.323
StartingPoint[3] = 20.85705
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),350,StartingFloat,true)